[package]
name = "ix"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.3"
actix = "0.13"
actix-broker = "0.4.3"
serialport = "4.2.0"
imc = {path = "../imc-rust" }